Repository sacloud/usacloud, pull requests merged in 2018-02, with the labels that each got.

#316 issueテンプレートを追加
  .github/ISSUE_TEMPLATE.md
Labels: area/docs

#318 Add --class option to startup-script
  command/cli/cli_startup_script_gen.go
  command/completion/startup_script_flags_gen.go
  command/funcs/startup_script_list_gen.go
  command/params/params_startup_script_gen.go
  define/parameters.go
  define/startup_script.go
  define/webaccel.go
Labels: area/commands

#319 Update copyright
  README.md
  main.go
Labels: area/docs, area/misc
