Repository sacloud/usacloud, pull requests merged in 2021-02, with the labels that each got.

#812 fix public-key handling
  pkg/cmd/commands/common/types.go
  pkg/cmd/commands/server/create.go
  pkg/cmd/commands/sshkey/create.go
  pkg/cmd/core/parameter_loader.go
  pkg/validate/dummy.pub
  pkg/validate/functions.go
  pkg/validate/functions_test.go
Labels: area/commands, bug, v1

#813 Convert target to map before calling gojq
  pkg/query/query.go
  pkg/query/query_test.go
Labels: area/core, bug, v1

#814 Colorize output of the rest command
  pkg/cmd/commands/rest/request.go
  pkg/query/query_test.go
Labels: area/commands, v1

#815 libsacloud v2.13
  go.mod
  go.sum
  vendor/github.com/sacloud/libsacloud/v2/sacloud/state.go
  vendor/github.com/sacloud/libsacloud/v2/version.go
  vendor/modules.txt
Labels: area/core, v1

#817 Fix cannot load current config
  pkg/config/config.go
Labels: area/core, bug, v1
